/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    berita: Berita;
    prestasi: Prestasi;
    guru: Guru;
    jabatan: Jabatan;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    berita: BeritaSelect<false> | BeritaSelect<true>;
    prestasi: PrestasiSelect<false> | PrestasiSelect<true>;
    guru: GuruSelect<false> | GuruSelect<true>;
    jabatan: JabatanSelect<false> | JabatanSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'school-profile': SchoolProfile;
  };
  globalsSelect: {
    'school-profile': SchoolProfileSelect<false> | SchoolProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Kelola berita dan pengumuman sekolah di sini.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "berita".
 */
export interface Berita {
  id: number;
  judul: string;
  /**
   * Diisi otomatis dari judul. Contoh: berita-penerimaan-siswa-baru
   */
  slug: string;
  /**
   * Upload atau pilih gambar utama untuk berita ini.
   */
  imageUrl: number | Media;
  /**
   * Deskripsi singkat berita (tampil di halaman daftar berita).
   */
  ringkasan?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tanggalPublikasi: string;
  status: 'draft' | 'published';
  penulis?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola berita prestasi siswa di sini.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prestasi".
 */
export interface Prestasi {
  id: number;
  prestasi: string;
  pemilik: string;
  /**
   * Diisi otomatis dari prestasi + pemilik. Contoh: osn-ipa-2026-namaSiswa
   */
  slug: string;
  /**
   * Upload atau pilih gambar utama untuk berita ini.
   */
  imageUrl: number | Media;
  /**
   * Deskripsi singkat berita prestasi.
   */
  ringkasan?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tanggalPublikasi: string;
  status: 'draft' | 'published';
  penulis?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola data guru dan pegawai sekolah di sini.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guru".
 */
export interface Guru {
  id: number;
  foto: number | Media;
  nama: string;
  /**
   * Nomor Induk Pegawai. Kosongkan jika tidak memiliki NIP.
   */
  nip?: string | null;
  jenis: 'guru' | 'pegawai';
  /**
   * Contoh: Matematika, Bahasa Indonesia
   */
  mengajar?: string | null;
  /**
   * Contoh: Staf TU, Satpam
   */
  posisi?: string | null;
  pendidikanTerakhir: 'sma' | 'd3' | 's1' | 's2' | 's3';
  /**
   * Contoh: 08123456789
   */
  nomorHp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola daftar jabatan untuk guru dan pegawai sekolah.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jabatan".
 */
export interface Jabatan {
  id: number;
  /**
   * Contoh: Kepala Sekolah, Guru Kelas 1, Staf TU
   */
  nama: string;
  /**
   * Pilih guru atau pegawai yang memegang jabatan ini.
   */
  guru?: (number | Guru)[] | null;
  /**
   * Digunakan untuk mengelompokkan jabatan di struktur organisasi.
   */
  divisi: 'pimpinan' | 'guru' | 'tata_usaha' | 'operator' | 'lainnya';
  /**
   * Angka lebih kecil tampil lebih awal dalam satu level.
   */
  urutan?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'berita';
        value: number | Berita;
      } | null)
    | ({
        relationTo: 'prestasi';
        value: number | Prestasi;
      } | null)
    | ({
        relationTo: 'guru';
        value: number | Guru;
      } | null)
    | ({
        relationTo: 'jabatan';
        value: number | Jabatan;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "berita_select".
 */
export interface BeritaSelect<T extends boolean = true> {
  judul?: T;
  slug?: T;
  imageUrl?: T;
  ringkasan?: T;
  body?: T;
  tanggalPublikasi?: T;
  status?: T;
  penulis?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prestasi_select".
 */
export interface PrestasiSelect<T extends boolean = true> {
  prestasi?: T;
  pemilik?: T;
  slug?: T;
  imageUrl?: T;
  ringkasan?: T;
  body?: T;
  tanggalPublikasi?: T;
  status?: T;
  penulis?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guru_select".
 */
export interface GuruSelect<T extends boolean = true> {
  foto?: T;
  nama?: T;
  nip?: T;
  jenis?: T;
  mengajar?: T;
  posisi?: T;
  pendidikanTerakhir?: T;
  nomorHp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jabatan_select".
 */
export interface JabatanSelect<T extends boolean = true> {
  nama?: T;
  guru?: T;
  divisi?: T;
  urutan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-profile".
 */
export interface SchoolProfile {
  id: number;
  name: string;
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  mobilePhone?: string | null;
  vision?: string | null;
  visionDescription?: string | null;
  mission?:
    | {
        text?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  fotoKepalaSekolah?: (number | null) | Media;
  sambutanKepalaSekolah?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  strukturOrganisasi?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-profile_select".
 */
export interface SchoolProfileSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  email?: T;
  phone?: T;
  mobilePhone?: T;
  vision?: T;
  visionDescription?: T;
  mission?:
    | T
    | {
        text?: T;
        description?: T;
        id?: T;
      };
  logo?: T;
  fotoKepalaSekolah?: T;
  sambutanKepalaSekolah?: T;
  strukturOrganisasi?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}